## 常用函数

In [1]:
import numpy as np

### 文件读写

In [10]:
# savetxt()函数
a = np.eye(2)
np.savetxt(fname="./dataset/eye.txt", X=a, fmt="%.2f")

In [12]:
# 加载csv文件
c, v = np.loadtxt(fname="dataset/data.csv", delimiter=",", usecols=(6, 7), unpack=True)
print(c, v)

[336.1  339.32 345.03 344.32 343.44 346.5  351.88 355.2  358.16 354.54
 356.85 359.18 359.9  363.13 358.3  350.56 338.61 342.62 342.88 348.16
 353.21 349.31 352.12 359.56 360.   355.36 355.76 352.47 346.67 351.99] [21144800. 13473000. 15236800.  9242600. 14064100. 11494200. 17322100.
 13608500. 17240800. 33162400. 13127500. 11086200. 10149000. 17184100.
 18949000. 29144500. 31162200. 23994700. 17853500. 13572000. 14395400.
 16290300. 21521000. 17885200. 16188000. 19504300. 12718000. 16192700.
 18138800. 16824200.]


In [13]:
# 计算成交量加权平均价
vwap = np.average(c, weights=v)
vwap

350.5895493532009

In [14]:
# 算术平均值
mean = np.mean(c)
mean

351.0376666666667

In [16]:
# 时间加权平均
twap = np.average(c, weights=np.arange(len(c)))
twap

352.4283218390804

### 最大值和最小值

In [17]:
h, l = np.loadtxt(fname="dataset/data.csv", delimiter=",", usecols=(4, 5), unpack=True)
h

array([344.4 , 340.04, 345.65, 345.25, 344.24, 346.7 , 353.25, 355.52,
       359.  , 360.  , 357.8 , 359.48, 359.97, 364.9 , 360.27, 359.5 ,
       345.4 , 344.64, 345.15, 348.43, 355.05, 355.72, 354.35, 359.79,
       360.29, 361.67, 357.4 , 354.76, 349.77, 352.32])

In [19]:
# 最大值
highest = np.max(h)
highest

364.9

In [20]:
# 最小值
lowest = np.min(l)
lowest

333.53

In [21]:
# 计算极差(最大值减去最小值)
ptp = np.ptp(h)
ptp

24.859999999999957

In [22]:
c = np.loadtxt(fname="dataset/data.csv", delimiter=",", usecols=(6,), unpack=True)
c

array([336.1 , 339.32, 345.03, 344.32, 343.44, 346.5 , 351.88, 355.2 ,
       358.16, 354.54, 356.85, 359.18, 359.9 , 363.13, 358.3 , 350.56,
       338.61, 342.62, 342.88, 348.16, 353.21, 349.31, 352.12, 359.56,
       360.  , 355.36, 355.76, 352.47, 346.67, 351.99])

In [23]:
# 获取中位数
median = np.median(c)
median

352.055

In [25]:
# 排序
sorted_close = np.msort(c)
sorted_close

array([336.1 , 338.61, 339.32, 342.62, 342.88, 343.44, 344.32, 345.03,
       346.5 , 346.67, 348.16, 349.31, 350.56, 351.88, 351.99, 352.12,
       352.47, 353.21, 354.54, 355.2 , 355.36, 355.76, 356.85, 358.16,
       358.3 , 359.18, 359.56, 359.9 , 360.  , 363.13])

In [26]:
middle = sorted_close[(len(c)) // 2]
middle

352.12

In [27]:
# 方差
variance = np.var(c)
variance


50.126517888888884