## NumPy基础

In [1]:
import numpy as np

In [2]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [3]:
# 查看数据类型
a.dtype

dtype('int64')

In [4]:
# 查看形状
a.shape

(5,)

In [5]:
# 创建多维数组
m = np.array([np.arange(2), np.arange(2)])
m

array([[0, 1],
       [0, 1]])

In [6]:
# 选取数据
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [7]:
# 选取第一行第一列
a[0, 0]

1

In [8]:
# 选取第一行第二列
a[0, 1]

2

In [9]:
# 指定类型创建数组
a = np.arange(7, dtype=np.int64)
a

array([0, 1, 2, 3, 4, 5, 6])

In [10]:
# 查看数据类型所占字节大小
a.dtype.itemsize

8

### 数组切片操作

In [11]:
a = np.arange(9)
a[3:7]

array([3, 4, 5, 6])

In [12]:
# 步长为2
a[3:7:2]

array([3, 5])

### 高维数组切片

In [13]:
a = np.arange(24).reshape(2, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [14]:
# 形状
a.shape

(2, 3, 4)

In [15]:
# 选取元素
a[0, 0, 0]

0

In [16]:
# 对于不关心的维度，可是使用冒号
a[:, 0, 0]

array([ 0, 12])

In [17]:
a[0, :, :] # 或者a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
a[0, ...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
# 步长为2
a[0, 1, ::2]

array([4, 6])

### 改变数组的形状

In [20]:
a = np.arange(24).reshape(2, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [21]:
# ravel函数
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [22]:
# flatten函数
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [23]:
# reshape函数
a.reshape(4, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [24]:
# 转置操作
a.transpose()

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [25]:
# resize函数
a.resize((2 ,12))
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

### 组合数组

In [26]:
a = np.arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
b = 2 * a
b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [28]:
# 水平组合
c = np.hstack((a, b))
c

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [29]:
# 水平组合
c = np.concatenate((a, b), axis=1)
c

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [30]:
# 垂直组合
c = np.vstack((a, b))
c

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [31]:
# 垂直组合
c = np.concatenate((a, b), axis=0)
c

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [32]:
# 深度组合
c = np.dstack((a, b))
c

array([[[ 0,  0],
        [ 1,  2],
        [ 2,  4]],

       [[ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16]]])

In [33]:
# 列组合(column_stack函数对于一维数组将按照列方向进行组合)
oned = np.arange(2)
twiced_oned = 2 * oned
c = np.column_stack((oned, twiced_oned))
c

array([[0, 0],
       [1, 2]])

In [34]:
# column_stack和hstack对于二维数组相同
a = np.arange(9).reshape(3, 3)
b = 2 * a
np.column_stack((a, b)) == np.hstack((a, b))

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [35]:
# 行组合
np.row_stack((oned, twiced_oned))

array([[0, 1],
       [0, 2]])

### 分割数组

In [36]:
a = np.arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
# 水平分割
np.hsplit(a, 3)

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

In [38]:
# 水平分割
np.split(a, 3, axis=1)

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

In [39]:
# 垂直分割
np.vsplit(a, 3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [40]:
# 垂直分割
np.split(a, 3, axis=0)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

### 数组属性

In [41]:
b = np.arange(24).reshape(2, -1)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [42]:
# ndim(轴的个数)
b.ndim

2

In [43]:
# size属性(元素个数)
b.size

24

In [44]:
# itemsize属性(元素再内存中所占有的字节数)
b.itemsize

8

In [45]:
# nbytes属性(数组所占据的所有内存字节数)
b.nbytes

192

### 数组的转换

In [46]:
b = np.array([1.+1.j, 3.+2.j])
b

array([1.+1.j, 3.+2.j])

In [47]:
# tolist()函数转换成python列表
b.tolist()

[(1+1j), (3+2j)]