Numpy库memmap函数学习

In [1]:
import numpy as np


def write():
    file = np.memmap("memmap.dat", dtype="float32", mode="w+", shape=(3, 4))
    print("写初始化:\n{}".format(file))

    data = np.arange(12, dtype="float32")
    data.resize((3, 4))
    file[:] = data[:]
    print("写结束:\n{}".format(file))

    file.flush()

def read():
    file = np.memmap("memmap.dat", dtype="float32", mode="r", shape=(3, 4))
    print("读:\n{}".format(file))

In [2]:
write()
read()

写初始化:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
写结束:
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
读:
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
